@startuml
left to right direction
skinparam packageStyle rectangle

actor 顾客 as Customer

rectangle 自动售货机系统 {
  (选择饮料) as (SelectBeverage)
  (投入硬币或纸币) as (InsertCoinsOrBills)
  (推出饮料) as (DispenseBeverage)
  (计算找零) as (CalculateChange)
  (移走硬币) as (RemoveCoins)
  (退币) as (ReturnCoins)

  Customer --> (SelectBeverage) : 选择饮料
  Customer --> (InsertCoinsOrBills) : 投入硬币或纸币
  (InsertCoinsOrBills) --> (DispenseBeverage) : 如果金额足够且饮料数量足够
  (InsertCoinsOrBills) --> (SelectBeverage) : 如果金额不足或饮料数量不足
  (DispenseBeverage) --> (CalculateChange) : 计算找零
  (CalculateChange) --> (RemoveCoins) : 移走硬币
  Customer --> (ReturnCoins) : 退币

}

note right of (SelectBeverage) : 选择所需购买的饮料及数量
note right of (InsertCoinsOrBills) : 投入1元硬币、10元纸币、50元纸币
note right of (DispenseBeverage) : 推出饮料
note right of (CalculateChange) : 计算找零
note right of (RemoveCoins) : 清空硬币器
note right of (ReturnCoins) : 退环顾客所投入的硬币

@enduml