@startuml
participant MainWindow as MW
participant BorrowDialog as BD
participant System as S
database Database as DB
participant MessageBox as MB
participant User

== 借阅图书流程 ==

MW -> BD: 按下“借阅图书”按钮
BD -> User: 输入借阅证件号码
User -> BD: 返回借阅证件号码
BD <-> S: 验证借阅证有效
S -> DB: 查询借阅证有效性
DB -> S: 返回借阅证有效性结果
alt 借阅证有效
    S -> BD: 借阅证有效
    BD -> User: 输入借阅书籍的ISBN号
    User -> BD: 返回ISBN号
    BD <-> S: 查询图书
    S -> DB: 根据ISBN号查询图书
    DB -> S: 返回图书信息
    S -> BD: 图书存在
    BD <-> S: 请求添加借阅记录
    S -> DB: 添加借阅记录
    DB -> S: 借阅记录添加成功
    S -> BD: 借阅成功
    BD -> MB: 创建借书成功提示
    MB -> User: 显示借书成功提示
else 借阅证无效
    S -> BD: 借阅证无效
    BD -> User: 显示借阅证无效提示
end
@enduml